### ISSUE TITLE
Npm@1 - Translation missing from debug call breaks build due to new warning

### ISSUE THREAD

**Issue by ncook-hxgn** [microsoft/azure-pipelines-tasks-common-packages#343]
There is a translated debug print statement here in `getSystemAccessToken()` in [locationUtilities.ts](https://github.com/microsoft/azure-pipelines-tasks-common-packages/blob/64b33d29c2475ae6d48abc882ec5e6f5f82168ea/common-npm-packages/packaging-common/locationUtilities.ts#L120), but the translation doesn't exist in [resources/en-US/resources.resjson](https://github.com/microsoft/azure-pipelines-tasks-common-packages/blob/64b33d29c2475ae6d48abc882ec5e6f5f82168ea/common-npm-packages/packaging-common/Strings/resources.resjson/en-US/resources.resjson)

This generates a warning `##[warning]Can't find loc string for key: Info_GotAndMaskAuth` which prevents us from merging changes due to the Build Quality Checks plugin preventing us from increasing the warning counts of our software builds.

Please fix the warning/add the missing translation

**Comment by ivanduplenskikh** [comment]
@ncook-hxgn, thanks for contribution! Let us take a look.
